version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: novi
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: slideshow-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://db:3306/novi
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: password
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/novi
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: password
    restart: on-failure

volumes:
  mysql_data: