DROP TABLE IF EXISTS proof_of_play;
DROP TABLE IF EXISTS slideshow_image;
DROP TABLE IF EXISTS slideshow;
DROP TABLE IF EXISTS image;

-- Image table
CREATE TABLE image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(1024) NOT NULL,
    duration INT NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Slideshow table
CREATE TABLE slideshow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Join table for slideshow <-> images (with custom duration)
CREATE TABLE slideshow_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slideshow_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,

    CONSTRAINT fk_slideshow FOREIGN KEY (slideshow_id) REFERENCES slideshow(id) ON DELETE CASCADE,
    CONSTRAINT fk_image FOREIGN KEY (image_id) REFERENCES image(id) ON DELETE CASCADE
);

-- Proof-of-play table
CREATE TABLE proof_of_play (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slideshow_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proof_slideshow FOREIGN KEY (slideshow_id) REFERENCES slideshow(id) ON DELETE CASCADE,
    CONSTRAINT fk_proof_image FOREIGN KEY (image_id) REFERENCES image(id) ON DELETE CASCADE
);